name: Artifacts Demo
on:
  issues:
    types: [opened,closed]
    

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run commands
        run: mkdir disc ; echo "Hello" > output.txt ; echo "hi"
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload file
          path: disc
        

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Display build job output
      run: cat output.txt