name: Artifacts Demo
on:
  issues:
    types: [opened,closed]
    

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run commands
        run: echo "Hello" > output.txt ; echo "hi"
        

  test:
    runs-on: windows-latest
    steps:
    - name: Display build job output
      run: cat output.txt