name: Artifacts Demo
on:
  issues:
    types: [opened,closed]
    

jobs:

  build:
    outputs:
      one: ${{steps.abc.outputs.test}}
    runs-on: windows-latest
    steps:
      - name: Run commands
        id: abc
        run: mkdir disc ; echo "test=Hello" >> "$GITHUB_OUTPUTS" ; echo "hi"
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload file
          path: disc
        

  # test:
  #   needs: build
  #   runs-on: windows-latest
  #   steps:
  #   - name: Display build job output
  #     run: cat output.txt