name: My_firstWorkflow
on:
  pull_request:
    types: [opened,reopened]
jobs:
  myfirst-job:
    runs-on: windows-latest
    steps:
        - name: My firstjob
          run: |
            echo "hello"
            echo "Hi"
        
