name: Environment Demo
on:
  workflow_dispatch

env:
  Name: Arpitha

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      Name: Anamika
    steps:
      - name: Enironment variable usage
        run: |
          echo "$Name $First_Name"
          echo "How are you $Name? who is the $GITHUB_ACTOR"
        env:
          First_Name: Mona
  Test:
    runs-on: windows-latest
    steps:
      - name: Check runner
        run: echo "Hi $env:Name and $env:RUNNER_OS name "
    
  
