name: Artifacts Demo
on:
  issues:
    types: [opened,closed]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      one: ${{ steps.step1.outputs.test }}
    steps:
        - name: Out generating
          id: step1
          run: |
            echo "test1=hello" >> "$GITHUB_OUTPUT"
            echo "test=world" >> "$GITHUB_OUTPUT"
        - name: Inside output display
          run: echo "${{steps.step1.outputs.tes1}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
        # - env:
        #     OUTPUT1: ${{needs.job1.outputs.output1}}
        #     OUTPUT2: ${{needs.job1.outputs.output2}}
        - name: Output Demo
          run: echo "${{needs.job1.outputs.one}}"
